In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [40]:
trainingSet = np.loadtxt("../trainingset/Understanding_Cost_Function_And_Gradient_Descent.txt", delimiter=",")



In [84]:
### y = mX + c or
### 
### y
###
###

'''
line eq, 
y = mX + c
or
y = B1X + B0

B0, B1 are coefficients 
B = [B0, B1, ....Bn]
X = [1,r1
     1,r2
     1,r3
     .,r4]
     
B = [
    B0,
    B1
    ]
    
for each point y'(y-hat or preddicted value) = x(i)B1 + B0

'''


"\nline eq, \ny = mX + c\nor\ny = B1X + B0\n\nB0, B1 are coefficients \nB = [B0, B1, ....Bn]\nX = [1,r1\n     1,r2\n     1,r3\n     .,r4]\n     \nB = [\n    B0,\n    B1\n    ]\n    \nfor each point y'(y-hat or preddicted value) = x(i)B1 + B0\n\n"

In [85]:
## Create X array as described above
'''
X = [1, r1
     1, r2
     1, r3
     1, ..
     1, rn]
'''
##trainingSet[:, 0] -   will column-0 of all rows
##np.ones(trainingSet.shape[0]) - create column of ones

# np.c_ = concatenate above stow columns

X = np.c_[np.ones(trainingSet.shape[0]), trainingSet[:, 0]]

# display 5 rows
X[0:5]

array([[ 1.    ,  6.1101],
       [ 1.    ,  5.5277],
       [ 1.    ,  8.5186],
       [ 1.    ,  7.0032],
       [ 1.    ,  5.8598]])

In [86]:
## Create y array as described above

# trainingSet[:,1] - get column-1 of all rows
# create column 
y = np.c_[trainingSet[:,1]]
y[0:5]

array([[ 17.592 ],
       [  9.1302],
       [ 13.662 ],
       [ 11.854 ],
       [  6.8233]])

In [106]:
'''
B = [
    B0,
    B1
    ]
    
'''

theta = np.zeros((2,1))
theta

h = X.dot(theta)
X.T.dot(h-y )

array([[ -566.3961    ],
       [-6336.89842532]])

In [98]:
## cost function
##1/2m * sum(h-y)^2

def cost_function(X,y,theta=[[0],[0]]):
    m = y.size
    h = X.dot(theta)
    J = 1/(2*m)*np.sum(np.square(h-y))
    return (J)
    

In [104]:
## gradient function
'''
theta=theta - alpha* costfunction

'''
X.T.shape

(2, 97)